# Understanding the Basics of Testing

- Go's testing support has two parts: 
  - libraries
  - tooling
- The `testing` package in the standard library provides the types and functions to write tests.
- The `go test` tool that's bundled with Go runs our tests and generates reports.
- Go places its tests in the same directory and the same package as the production code.
  - Thus, tests are able to access and test unexported functions and variables.
- Every test is written in a file whose name ends with `_test.go`.
  - For example, if we are writing tests against `foo.go`, place it in a file named `foo_test.go`.

`adder/adder.go`

```go
package adder

func addNumbers(x, y int) int{
	return x + x
}
```

`adder/adder_test.go`

- Test functions start with the word `Test` and take in a single parameter of type `*testing.T`.
- Test functions do not return any values.

```go
package adder

import "testing"

func Test_addNumbers(t *testing.T){
	result := addNumbers(2, 3)
	if result != 5{
		t.Error("incorrect result: expected 5, got", result)
	}
}
```

```sh
practice ➤ go test ./adder -v
=== RUN   Test_addNumbers
    adder_test.go:8: incorrect result: expected 5, got 4
--- FAIL: Test_addNumbers (0.00s)
FAIL
FAIL    practice/adder  0.001s
FAIL
```

- But if we fix our `addNumbers`:

```sh
practice ➤ go test ./adder -v
=== RUN   Test_addNumbers
--- PASS: Test_addNumbers (0.00s)
PASS
ok      practice/adder  0.001s
```

- We can use `Errorf` method for  Printf-style formatting string to generate our message too.

```go
t.Errorf("incorrect result: expected %d, got %d", 5, result)
```

- However, the test function continues running when `Error` and `Errorf` mark a test as failed.
- To stop a test function from processing as soon as a failure is found, we can use `Fatal` and `Fatalf`.