# Wrapping Errors

- In Go, **error wrapping** lets us add context to an existing error while still retaining the ability to inspect or match the original (“inner”) error. 
- This creates a chain of errors, where each layer of wrapping provides additional details about what was happening when the error occurred, without losing the original cause.
- Basically, a wrapped error is simply an error value that carries another inner error along with it.
- Formalized in Go 1.13 with the `%w` verb in `fmt.Errorf` and the functions in the `errors` package.
- When we have a series of wrapped errors, it's called an **error tree**.
- The standard library also provides a function for unwrapping errors, the `Unwrap` function in the `errors` package.
  - Pass it an error, and it returns the wrapped error if there's one. 
  - If there isn't, it returns `nil`.
- When to wrap?:
  - **Add context**: every time we return an error up the call stack, wrap it so callers know *what* operation failed.
  - **Preserve the original**: don’t lose the sentinel or custom error we might need to match.


---

## Code Example

- The following code demonstrates wrapping with `fmt.Errorf` and unwrapping with `errors.Unwrap`.

```go
package main

import (
	"errors"
	"fmt"
	"os"
)

func fileChecker(name string) error {
	f, err := os.Open(name)
	if err != nil {
		return fmt.Errorf("in fileChecker: %w", err)
	}
	f.Close()
	return nil
}

func main() {
	err := fileChecker("file.txt")
	if err != nil {
		fmt.Println(err)
		if wrappedErr := errors.Unwrap(err); wrappedErr != nil {
			fmt.Println(wrappedErr)
		}
	}
}
```

```sh
chan@CMA:~/Go_Programming/ch1$ make
go fmt ./...
hello.go
go vet ./...
go build
chan@CMA:~/Go_Programming/ch1$ ./hello_world
in fileChecker: open file.txt: no such file or directory
open file.txt: no such file or directory
```

---

