# Wrapping Errors with defer

- If we find ourselves wrapping multiple errors with the same message, we can simplify by using defer.
- We have to name the return values so that we can refer to `err` in the deferred function. 
- If we anme a single return value, we must name all of them, so here we use an underscore fort he string return value that isn't explictly assigned.

```go
package main

import (
	"errors"
	"fmt"
)

func DoSomeThings(val1 int, val2 string) (_ string, err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("in doSomethings: %w", err)
		}
	}()
	val3, err := DoThing1(val1)
	if err != nil {
		return "", err
	}
	val4, err := doThing2(val2)
	if err != nil {
		return "", err
	}
	return doThing3(val3, val4)
}

func DoThing1(val int) (int, error) {
	if val < 0 {
		return 0, fmt.Errorf("doThing1: negative input %d", val)
	}
	return val * 2, nil
}

func doThing2(s string) (string, error) {
	if s == "" {
		return "", errors.New("doThing2: empty string")
	}
	return s + " proccessed", nil
}

func doThing3(val1 int, val2 string) (string, error) {
	return fmt.Sprintf("result = %d | %s", val1, val2), nil
}

func main() {
	tests := []struct {
		x int
		y string
	}{
		{10, "foo"},
		{10, ""},
		{-5, "bar"},
	}

	for _, tc := range tests {
		out, err := DoSomeThings(tc.x, tc.y)
		if err != nil {
			fmt.Printf("DoSomeThings(%d, %q), error: %v\n", tc.x, tc.y, err)
		} else {
			fmt.Printf("DoSomeThings(%d, %q) = %q\n", tc.x, tc.y, out)
		}
	}
}
```

```sh
chan@CMA:~/Go_Programming/ch1$ make
go fmt ./...
go vet ./...
go build
chan@CMA:~/Go_Programming/ch1$ ./hello_world
DoSomeThings(10, "foo") = "result = 20 | foo proccessed"
DoSomeThings(10, ""), error: in doSomethings: doThing2: empty string
DoSomeThings(-5, "bar"), error: in doSomethings: doThing1: negative input -5
```



